# Generated by Django 5.2.1 on 2025-11-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('site_name', models.CharField(blank=True, help_text='Optional', max_length=200, null=True)),
                ('project_name', models.CharField(blank=True, help_text='Optional', max_length=500, null=True)),
                ('lot_number', models.CharField(blank=True, help_text='Optional', max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('LC', 'Letter of Credit'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit_days', models.IntegerField(blank=True, null=True)),
                ('contract_currency', models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', max_length=10)),
                ('sign_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer')),
            ],
        ),
    ]
