# Generated by Django 5.2.1 on 2025-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='VRN',
            field=models.CharField(blank=True, help_text='eg. xx-xxxxxx-x', max_length=12, null=True, unique=True),
        ),
    ]
