# Generated by Django 5.2.1 on 2025-11-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_delivered_quantity_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered_quantity',
        ),
    ]
