# Generated by Django 5.2.1 on 2025-11-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0006_remove_orderitem_delivered_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=20, unique=True, verbose_name='发货单号')),
                ('delivery_date', models.DateField(verbose_name='发货日期')),
                ('status', models.CharField(choices=[('PENDING', '待发货'), ('IN_TRANSIT', '运输中'), ('DELIVERED', '已送达'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='customers.customer', verbose_name='客户')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '发货单',
                'verbose_name_plural': '发货单',
                'db_table': 'deliveries',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.PositiveIntegerField(verbose_name='发货数量')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.delivery', verbose_name='发货单')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='orders.orderitem', verbose_name='订单项')),
            ],
            options={
                'verbose_name': '发货项',
                'verbose_name_plural': '发货项',
                'db_table': 'delivery_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
