# Generated by Django 5.2.1 on 2025-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='司机姓名'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_phone',
            field=models.CharField(default='', max_length=20, verbose_name='司机电话'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_number',
            field=models.CharField(default='', max_length=50, verbose_name='货车号码'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='发货单号'),
        ),
    ]
