# Generated by Django 5.2.1 on 2025-11-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_vrn'),
        ('deliveries', '0002_delivery_driver_name_delivery_driver_phone_and_more'),
        ('orders', '0006_remove_orderitem_delivered_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_date', '-created_at'], 'verbose_name': 'Delivery Order', 'verbose_name_plural': 'Delivery Orders'},
        ),
        migrations.AlterModelOptions(
            name='deliveryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivery Item', 'verbose_name_plural': 'Delivery Items'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Delivery Number'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='driver_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Driver Phone'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='vehicle_number',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle Number'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(verbose_name='Delivered Quantity'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.delivery', verbose_name='Delivery Order'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
