# Generated by Django 5.2.1 on 2025-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('M', 'M'), ('KM', 'KM'), ('KG', 'KG'), ('PK', 'Package'), ('LT', 'Liter'), ('PC', 'Piece'), ('TSH', 'TSH'), ('SET', 'SET')], max_length=10)),
                ('stock_quantity', models.CharField(blank=True, help_text='Optional', max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
